# .github/workflows/deploy.yml
name: Deploy Image

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      container_name:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      EC2_HOST:
        required: true
      EC2_USERNAME:
        required: true
      FIREBASE_SERVICE_ACCOUNT_JSON:
        required: true
      ACC_TOKEN:
        required: true
      AUTH_CLIENT_ID:
        required: true
      AUTH_CLIENT_SECRET:
        required: true
      AUTH_CLIENT_URL:
        required: true
      DOCKER_REPO:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            CONTAINER_NAME="${{ inputs.container_name }}"
            IMAGE_TAG="${{ secrets.DOCKER_REPO }}:${{ inputs.image_tag }}"
            IMAGE_EXISTING_PREFIX="${{ secrets.DOCKER_REPO}}:${{ inputs.branch_name }}-"

            docker images --format "{{.Repository}}:{{.Tag}}" | \
            grep "^${IMAGE_EXISTING_PREFIX}" | \
            xargs -r docker rmi || true
            echo "Old images removed."

            docker stop "${CONTAINER_NAME}" || true
            docker rm "${CONTAINER_NAME}" || true
            docker pull "${IMAGE_TAG}"
            
            # Generate random port antara 5000 dan 8500
            while :
            do
              PORT_HOST=$(( ( RANDOM % 3500 ) + 5000 ))
              if ! ss -tuln | grep -q ":$PORT_HOST "; then
                break
              fi
            done
            echo "Random available port selected: $PORT_HOST"

            docker run -d \
              -p ${PORT_HOST}:${{ vars.PORT }} \
              --network tunnel \
              --name "${CONTAINER_NAME}" \
              --restart unless-stopped \
              -e NODE_ENV=development \
              -e ORGS_NAME="${{ vars.ORGS_NAME }}" \
              -e PORT="${{ vars.PORT }}" \
              -e ACC_TOKEN="${{ secrets.ACC_TOKEN }}" \
              -e AUTH_CLIENT_ID="${{ secrets.AUTH_CLIENT_ID }}" \
              -e AUTH_CLIENT_SECRET="${{ secrets.AUTH_CLIENT_SECRET }}" \
              -e AUTH_CLIENT_URL="${{ secrets.AUTH_CLIENT_URL }}" \
              -e FIREBASE_SERVICE_ACCOUNT_JSON="$(echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' | jq -c .)" \
              "${IMAGE_TAG}"
            echo "Deployment completed successfully."

            docker image prune -f
            echo "Old images pruned."
